// List of keywords related to electrical subjects
List<String> electricalKeywords = [
  'electronics',
  'circuit',
  'electric',
  'electrical',
  'emf',
  'voltage',
  'current',
  'resistor',
  'capacitor',
  'inductor',
  'transformer',
  'electricity',
  'amperage',
  'conductor',
  'semiconductor',
  'insulator',
  'transistor',
  'diode',
  'ohm',
  'watt',
  'farad',
  'henry',
  'rectifier',
  'relay',
  'switch',
  'breaker',
  'fuse',
  'generator',
  'motor',
  'battery',
  'alternator',
  'solenoid',
  'inductance',
  'resistance',
  'impedance',
  'electromagnetic',
  'magnet',
  'coil',
  'oscillator',
  'frequency',
  'hertz',
  'phases',
  'AC',
  'DC',
  'analog',
  'digital',
  'signal',
  'ground',
  'neutral',
  'live',
  'multimeter',
  'oscilloscope',
  'schematic',
  'VLSI',
  'microcontroller',
  'microprocessor',
  'embedded',
  'sensor',
  'actuator',
  'LED',
  'LCD',
  'filament',
  'cathode',
  'anode',
  'breadboard',
  'PCB',
  'copper',
  'aluminum',
  'zinc',
  'cable',
  'wire',
  'connector',
  'plug',
  'socket',
  'clamp',
  'clip',
  'power',
  'energy',
  'voltmeter',
  'ammeter',
  'wattmeter',
  'inverter',
  'converter',
  'rectifier',
  'thyristor',
  'SCR',
  'TRIAC',
  'MOSFET',
  'IGBT',
  'logic',
  'gate',
  'amplifier',
  'modulator',
  'demodulator',
  'encoder',
  'decoder',
  'multiplexer',
  'demultiplexer',
  'bus',
  'interface',
  'port',
  'UART',
  'SPI',
  'I2C',
  'PWM',
  'ADC',
  'DAC',
  'feedback',
  'loop',
  'filter',
  'bandwidth',
  'noise',
  'harmonics',
  'waveform',
  'sine',
  'square',
  'triangle',
  'reactance',
  'Q-factor',
  'potentiometer',
  'varistor',
  'thermistor',
  'photoresistor',
  'optocoupler',
  'isolation',
  'charge',
  'discharge',
  'surge',
  'spark',
  'static',
  'arc',
  'flux',
  'magnetic field',
  'electromotive',
  'ferrite',
  'core',
  'winding',
  'step-up',
  'step-down',
  'solder',
  'flux',
  'terminal',
  'junction',
  'short circuit',
  'open circuit',
  'Kirchhoff',
  'Ohm\'s Law',
  'Thevenin',
  'Norton',
  'Maxwell',
  'Laplace',
  'Fourier',
  'Tesla',
  'Faraday',
  'Helmholtz',
  'Lenz',
  'Superconductor',
  'Hall Effect',
  'Seebeck Effect',
  'Joule Heating',
  'Skin Effect',
  'Radiation',
  'Eddy Current',
  'Magnetic Hysteresis',
  'Ballast',
  'Choke',
  'Cross-talk',
  'Dielectric',
  'Galvanometer',
  'Piezoelectric',
  'Yagi',
  'Doppler Effect',
  'Varicap',
  'Waveguide',
  'Zener',
  'PLC',
  'RTU',
  'SCADA',
  'Servo',
  'Stepper',
  'HMI',
  'Contactor',
  'Phasor',
  'Vector',
  'Calibration',
  'Coupling',
  'Decoupling',
  'Attenuation',
  'FET',
  'BJT',
  'SMT',
  'THT',
  'RMS',
  'ASIC',
  'FPGA',
  'Microgrid',
  'PID Controller',
  'Quartz',
  'Op-Amp',
  'Darlington',
  'Cascode',
  'Bode Plot',
  'Nyquist',
  'Litz Wire',
  'Rheostat',
  'Tellegen',
  "  Balun",
  "Varactor",
  "Varistor",
  "Varicap",
  "Reactance",
  "Impediment",
  "Dielectric",
  "Permeability",
  "Permittivity",
  "Piezoelectricity",
  "Ferroelectricity",
  "Parametric",
  "Hysteresis",
  "Eddy current",
  "Skin effect",
  "Proximity effect",
  "Litz wire",
  "Stripline",
  "Coplanar",
  "Lumped element",
  "Distributed element",
  "Smith chart",
  "Phasor",
  "Reactance",
  "Susceptance",
  "Admittance",
  "Maxwell's equations",
  "Poynting vector",
  "Evanescent field",
  "Cascaded filters",
  "Group delay",
  "Insertion loss",
  "VSWR",
  "Stub matching",
  "Coupling coefficient",
  "Q factor",
  "Superheterodyne",
  "Direct digital synthesis",
  "Nyquist rate",
  "Aliasing",
  "Quantization error",
  "Dither",
  "Hall effect sensor",
  "Magnetoresistance",
  "Cryoelectronics",
  "Coulomb blockade",
  "Quantum tunneling",
  "Bloch oscillations",
  "Magnetowetting",
  "Spin torque",
  "Spintronics",
  "Plasmonics",
  "Magnonics",
  "Skyrmion",
  "Anyon",
  "Flexible electronics",
  "Molecular electronics",
  "Optoelectronics",
  "Photonics",
  "Plasmons",
  "Excitons",
  "Polariton",
  "Brillouin zone",
  "Quantum well",
  "Quantum wire",
  "Quantum dot",
  "Quantum cascade laser",
  "Unijunction transistor",
  "Tunnel diode",
  "Gunn diode",
  "IMPATT diode",
  "PIN diode",
  "Schottky diode",
  "Zener diode",
  "Avalanche diode",
  "Step recovery diode",
  "Pockels effect",
  "Kerr effect",
  "Franz-Keldysh effect",
  "Quantum Hall effect",
  "Aharonov-Bohm effect",
  "Metal–oxide–semiconductor (MOS)",
  "High-k dielectric",
  "III-V semiconductors",
  "Heterojunction",
  "Czochralski process",
  "Molecular beam epitaxy",
  "Chemical vapor deposition",
];
